### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by SkullMasher** [amercier/generator-webapp-php#5]
This happen on grunt serve. 'grunt' and 'grunt test' are working well.

```
Running "php:server" (php) task

C:\xampp\htdocs\imagehoster\node_modules\grunt-contrib-compass\node_modules\tmp\lib\tmp.js:261
  throw err;
        ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

Compass version is Compass 1.0.1.

I'm on Windows 10 Tech preview.

**Comment by mirkojovanovic** [comment]
I have same issue on windows 8.1. I'm using compass 1.0.3. Any help? Is this known issue?
